FROM python:3.6-alpine

WORKDIR /usr/src/app

COPY . .

RUN apk update 
RUN apk add gcc 
RUN apk add make 
RUN apk add iptables
RUN apk add iproute2
RUN apk add libaio-dev
RUN apk add libapparmor-dev 
RUN apk add libattr1-dev
RUN apk add libbsd-dev
RUN apk add libcap-dev
RUN apk add libgcrypt11-dev
RUN apk add libipsec-mb-dev
RUN apk add libkeyutils-dev
RUN apk add libsctp-dev
RUN apk add zlib1g-dev

RUN pip install --no-cache-dir -r requirements.txt
RUN cd anomalies/c_src && rm -fr stress-ng && git clone https://github.com/ColinIanKing/stress-ng.git && \
    cd stress-ng && make && cd /usr/src/app
RUN cd anomalies/c_src && rm -fr cpulimit && git clone https://github.com/opsengine/cpulimit.git && \
    cd cpulimit && make && cd /usr/src/app
RUN ./make.sh

ENTRYPOINT [ "python3.6", "./injector_agent.py" ]
